Vagrant.configure("2") do |config|
  config.vm.provision "file", source: "~/.ssh/tms_ssh.pub", destination: "~/.ssh/tms_ssh.pub"
  config.vm.provision "shell", inline: "cat /home/vagrant/.ssh/tms_ssh.pub >> /home/vagrant/.ssh/authorized_keys", run: "always"
  
  config.vm.define "ub" do |ub|
    ub.vm.box = "ubuntu/bionic64"
    ub.vm.hostname = "ubu-kodzimo"
    ub.vm.provision "shell", :inline =>
    "sudo chmod 644 ~/.ssh/authorized_keys
    sudo chown -R vagrant:vagrant ~/.ssh"
    ub.vm.network "private_network", ip: "192.168.56.20", bridge: "en0: Wi-Fi"
    ub.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
      v.name = "ubu_kodzimo"
    end
  end

  config.vm.define "cent" do |cent|
  cent.vm.box = "centos/7"
  cent.vm.hostname = "cent-kodzimo"
  cent.vm.network "private_network", ip: "192.168.56.2", bridge: "en0: Wi-Fi"
  cent.vm.provision "shell", :inline => 
  "sudo timedatectl set-timezone Australia/Darwin
  sudo yum install -y nano"
  cent.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
      v.name = "cent_kodzimo"
    end
  end
end