Vagrant.configure("2") do |config|
  config.vm.provision "file", source: "~/.ssh/tms_ssh.pub", destination: "~/.ssh/tms_ssh.pub"
  config.vm.provision "shell", inline: "cat /home/vagrant/.ssh/tms_ssh.pub >> /home/vagrant/.ssh/authorized_keys"
  
  config.vm.define "raid-learn" do |node|
    node.vm.synced_folder "C:/tms/lesson3/raid/share", "/home/vagrant/share"
    node.vm.box = "ubuntu/bionic64"
    node.vm.hostname = "raid-hw3"
    node.vm.network "private_network", ip: "192.168.23.20", bridge: "en0: Wi-Fi"
    node.vm.provider :virtualbox
  
    node.vm.disk :disk, size: "5GB", name: "extra_storage1"
    node.vm.disk :disk, size: "3GB", name: "extra_storage2"
    # node.vm.provision "shell", :inline => 
    # "sudo yum install -y nano
    # sudo yum install -y lvm2"
    node.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
      # v.customize ["storagectl", :id, "--name", "SCSI"]
      v.memory = 512
      v.cpus = 1
      v.name = "raid-learn"
    end
  end
end