---
- include_tasks: update_packages_deb.yml
  when: ansible_facts['os_family'] == "Debian"

- include_tasks: update_packages_rh.yml
  when: ansible_facts['os_family'] == "RedHat"
  
- include_tasks: user_creation.yml
  
