Vagrant.configure("2") do |config|
  config.vm.provision "file", source: "~/.ssh/tms_ssh.pub", destination: "~/.ssh/tms_ssh.pub"
  config.vm.provision "shell", inline: "cat /home/vagrant/.ssh/tms_ssh.pub >> /home/vagrant/.ssh/authorized_keys"
  
  config.vm.define "ubu-serv" do |serv|
    serv.vm.synced_folder "C:/tms/lesson4/share-serv", "/home/vagrant/share"
    serv.vm.box = "ubuntu/bionic64"
    serv.vm.hostname = "ntp-server"
    serv.vm.network "private_network", ip: "192.168.11.20", bridge: "en0: Wi-Fi"
    serv.vm.provision "shell", path: "/tms/lesson4/share-serv/ntp_sis.sh"
    serv.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 1
      v.name = "ntp_server"
    end
  end

  config.vm.define "ubu-cli" do |cli|
    cli.vm.synced_folder "C:/tms/lesson4/share-cli", "/home/vagrant/share"
    cli.vm.box = "ubuntu/bionic64"
    cli.vm.hostname = "ntp-client"
    cli.vm.network "private_network", ip: "192.168.11.2", bridge: "en0: Wi-Fi"
    cli.vm.provision "shell", path: "/tms/lesson4/share-cli/ntp_cis.sh"
    cli.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 1
      v.name = "ntp_client"
    end
  end
end