Vagrant.configure("2") do |config|
  config.vm.provision "file", source: "~/.ssh/tms_ssh.pub", destination: "~/.ssh/tms_ssh.pub"
  config.vm.provision "shell", inline: "cat /home/vagrant/.ssh/tms_ssh.pub >> /home/vagrant/.ssh/authorized_keys"

  config.vm.define "diskmgmt" do |node|
    node.vm.synced_folder "C:/tms/lesson3/lvm/share", "/home/vagrant/share"
    node.vm.box = "centos/7"
    node.vm.hostname = "tms-hw3"
    node.vm.network "private_network", ip: "192.168.23.2", bridge: "en0: Wi-Fi"
    node.vm.provider :virtualbox

    node.vm.disk :disk, size: "7GB", name: "extra_storage1"
    node.vm.disk :disk, size: "3GB", name: "extra_storage2"
    node.vm.provision "shell", :inline => 
    "sudo yum install -y nano
    sudo yum install -y lvm2"
    node.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 1
      v.name = "diskmgmt"
    end
  end
end